CREATE TABLE IF NOT EXISTS transcriber_grade_rates (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  grade_level INT NOT NULL,
  per_minute_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_transcriber_grade_rates_level (grade_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
